### ISSUE TITLE
handlebars isn't working

### ISSUE THREAD

**Issue by flyingwolf1701** [bradtraversy/storybooks#38]
Hello, I have been trying to get handlebar-express working with this app. I have tried to do it exactly the way brad has it, and I have copied it in from handlebars npm docs.

lastly I copied the code directly in from the github.

`const exphbs = require('express-handlebars');`

```
app.engine('.hbs', exphbs())
app.set('view engine', '.hbs')
```
with this one is is telling me that the app crashed - waiting for file changes before starting. and it is pointing at `storybook-project\app.js:35
    exphbs(
    ^`
 saying TypeError: exphbs is not a function

its kind of working when I use 
`var hbs = require('hbs')`

```
// app.set('view engine', 'hbs')
// app.set('views', './views')
```
but when I use this the css styling isn't working. I have googled everything I can think of, but I can't figure this out.

**Comment by vheyam** [comment]
totally sucks same issue, perhaps this tutorial is too advanced for me

**Comment by flyingwolf1701** [comment]
Anyone who reads this its just because all the versions have updated so much of this depreciated. You have to use the same version as him to get the same results.

**Comment by wfeliciano20** [comment]
Following the docs, you can achieve the desired result by
import { create } from 'express-handlebars';


const hbs = create({ defaultLayout: 'main',
    extname: '.hbs',});

// Register `hbs.engine` with the Express app.
app.engine('handlebars', hbs.engine);

**Comment by Crypto-Ash** [comment]
@wfeliciano20 Thanks, Bro! U Saved My Day ♥

**Comment by fernandonunespro** [comment]
> Following the docs, you can achieve the desired result by import { create } from 'express-handlebars';
> 
> const hbs = create({ defaultLayout: 'main', extname: '.hbs',});
> 
> // Register `hbs.engine` with the Express app. app.engine('handlebars', hbs.engine);

Thanks for that

**Comment by deepakabari** [comment]
i uses const { engine } = require("handlebars");
app.engine("hbs", engine({ extname: "hbs", defaultLayout: false }));

but the same problem occurs: 
TypeError: engine is not a function

I used this package because I got an error in express-handlebars when I used hbs.compile() function and the error got like compile is not a function
