### ISSUE TITLE
saving tags inside the database without sanatizing

### ISSUE THREAD

**Issue by hamid814** [bradtraversy/storybooks#6]
I noticed you can save tags inside the database without being sanitized into "& l t ;" or sth like that,
that can be used by attackers in production mode, to inject js code written by others, to run on other users machines

can you notify me if I'm wrong and it gets sanitized, and where it gets sanitized?

**Comment by herberthk** [comment]
@hamid814  i fixed this issue in this pull request https://github.com/bradtraversy/storybooks/pull/8  ask brad to merge it

**Comment by hamid814** [comment]
@herberthk , I took look at pull request #8 and I didn't see anything related to the sanitization of the inputs...

I also I don't think brad will aprove a change in config example or package.json

**Comment by herberthk** [comment]
@hamid814 mongoDb is not like SQL based databases which are prone to SQL injections  so there is no security risk associated with this in fact mongoose performs hard parts of security.

**Comment by hamid814** [comment]
@herberthk ,
Thats alright then, it seemswas it was my misunderstanding...
