### ISSUE TITLE
error at npm start

### ISSUE THREAD

**Issue by Vinay0001** [bradtraversy/storybooks#7]
after installing the dependencies and adding mongoDB URI and Google OAuth credentials to the config.env file when we do npm start this happens 

npm start
npm WARN lifecycle The node binary used for scripts is C:\Program Files\heroku\client\bin\node.exe but npm is using C:\Program Files\nodejs\node.exe itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> storybooks@1.0.0 start C:\Users\Vinay\Downloads\storybooks-master
> cross-env NODE_ENV=production node app

events.js:287
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES: permission denied 3000;
    at Server.setupListenHandle [as _listen2] (net.js:1296:21)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1460:5)
    at Function.listen (C:\Users\Vinay\Downloads\storybooks-master\node_modules\express\lib\application.js:618:24)
    at Object.<anonymous> (C:\Users\Vinay\Downloads\storybooks-master\app.js:100:5)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1340:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: '3000;',
  port: -1
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! storybooks@1.0.0 start: `cross-env NODE_ENV=production node app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the storybooks@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Vinay\AppData\Roaming\npm-cache\_logs\2020-07-22T10_28_18_929Z-debug.log

**Comment by Aayu8982** [comment]
{
  "name": "story-book",
  "version": "1.0.0",
  "description": "public and private storybook",
  "main": "app.js",
  "scripts": {
    "start": "cross-env NODE_ENV=production node app",
    "dev": "cross-env NODE_ENV=development nodemon app"
  },
  "author": "Aayush Sharma",
  "license": "MIT",
  "dependencies": {
    "connect-mongo": "^3.2.0",
    "dotenv": "^8.2.0",
    "express": "^4.17.1",
    "express-handlebars": "^4.0.4",
    "express-session": "^1.17.1",
    "method-override": "^3.0.0",
    "moment": "^2.27.0",
    "mongoose": "^5.9.19",
    "morgan": "^1.10.0",
    "passport": "^0.4.1",
    "passport-google-oauth20": "^2.0.0"
  },
  "devDependencies": {
    "cross-env": "^7.0.2",
    "nodemon": "^2.0.4"
  }
}

**Comment by howdyAnkit** [comment]
@Vinay0001 try to run on DIfferent Port or Maybe that port is busy.
Also, Brad has removed his Config keys try to change them before connecting

**Comment by hamid814** [comment]
@Vinay0001 I installed the app with npm and it worked just fine...

It seems the port 3000 on your computer has been taken by another app...

Run `netstat -ano | findstr :3000` to see if any app is running on that port

And to close the app running on that port, run `taskkill /PID [tcp] /F`. And instead of [tcp] put the number returned in last command

Hope this helps...

**Comment by Vinay0001** [comment]
thanks
